local M = {
   user = {
      no_search_highlight = "<ESC>",
      prev_jump_position = "[j",
      next_jump_position = "]j",
      increase_window_height = "<UP>",
      decrease_window_height = "<DOWN>",
      increase_window_width = "<RIGHT>",
      decrease_window_width = "<LEFT>",
      focus_on_current_fold = "<LEADER>zc",
   },
   plugin = {
      bbye = {
	 delete = "<leader>x",
	 wipeout = "<leader>X",
	 delete_all = "<leader>bx"
      },
      bufferline = {
         cycle_next = "<TAB>",
         cycle_prev = "<S-TAB>",
         move_next = "<leader>b<TAB>",
         move_prev = "<leader>bb<TAB>",
         sort_extension = "<leader>bse",
         sort_directory = "<leader>bsd",
      },
      cheatsheet = {
         default_keys = "<leader>dk",
         user_keys = "<leader>uk",
      },
      comment = { toggle = "<Leader>/" },
      coq = {
	 pum_escape = "<ESC>",
	 pum_cancel = "<C-c>",
	 pum_next = "<TAB>",
	 pum_previous = "<S-TAB>",
	 pum_select = "<CR>",
	 pum_backspace = "<BS>",
      },
      dap = {
	 toggle_breakpoint = "<leader>db",
         continue = "<leader>dc",
         step_out = "<leader>dsu",
         step_into = "<leader>dsi",
         step_over = "<leader>dso",
         launch_repl = "<leader>dr",
         test_python_method = "<leader>dtm",
         test_python_class = "<leader>dtc",
         debug_python_selection = "<leader>ds",
      },
      dashboard = {
	 open = "<leader>hh",
         bookmarks = "<leader>hm",
         new_file = "<leader>hf",
         session_load = "<leader>hl",
         session_save = "<leader>hs",
      },
      fugitive = {
	 git_status = "<leader>gg",
         git_add = "<leader>ga",
         git_commit = "<leader>gc",
         git_blame = "<leader>gb",
         git_diff = "<leader>gd",
         git_diff_split = "<leader>gds",
         git_diff_get_left = "<leader>gf",
         git_diff_get_right = "<leader>gh",
         git_edit = "<leader>ge",
         git_log = "<leader>gl",
         git_branch = "<leader>gbr",
         git_checkout = "<leader>go",
         git_push = "<leader>gps",
         git_pull = "<leader>gpl",
      },
      harpoon = {
	 add_file = "<leader>a",
         toggle_quick_menu = "<leader>mm",
         navigate_to_file_1 = "<leader>ma",
         navigate_to_file_2 = "<leader>ms",
         navigate_to_file_3 = "<leader>md",
         navigate_to_file_4 = "<leader>mf",
         navigate_to_file_5 = "<leader>mj",
         navigate_to_file_6 = "<leader>mk",
         navigate_to_file_7 = "<leader>ml",
         navigate_to_file_8 = "<leader>m;",
      },
      lsp = {
         open_float = "<leader>e",
         goto_prev = "[d",
         goto_next = "]d",
         set_loclist = "<leader>q",
	 declaration = "gD",
         definition = "gd",
         hover = "K",
         implementation = "gi",
         signature_help = "gs",
         add_workspace_folder = "<leader>awf",
         remove_workspace_folder = "<leader>rwf",
         list_workspace_folders = "<leader>lwf",
         type_definition = "<leader>D",
         rename = "<leader>rn",
         code_action = "<leader>ca",
         references = "gr",
         format = "<leader>cf",
         range_code_action = "<leader>ca",
      },
      markdown_preview = {
	 start_preview = "<Leader>vp",
	 stop_preview = "<Leader>vs",
	 toggle_preview = "<Leader>vv",
      },
      neoformat = { format = "<Leader>nf" },
      sandwich = {
	 auto_inner = "is",
	 auto_all = "as",
	 query_inner = "iz",
	 query_all = "az",
      },
      subversive = {
	 substitute = "s",
	 substitute_line = "ss",
	 substitute_end_of_line = "S",
      },
      telescope = {
	 buffers = "<leader>fb",
         find_files = "<leader>ff",
         find_hidden_files = "<leader>FF",
         find_projects = "<leader>fp",
         file_browser = "<leader>ft",
         git_commits = "<leader>fc",
         git_status = "<leader>fs",
         live_grep = "<leader>fg",
         oldfiles = "<leader>fo",
         help_tags = "<leader>fh",
         frecency = "<leader>fr",
         lsp_reference = "<leader>fl",
      },
      todo = { search_with_telescope = "<Leader>fd" },
      toggleterm = {
	 toggle = "<Leader>tt",
	 term = {
	    escape = "<ESC>",
	    normal_mode = "jk",
	    insert_exit_toggle = "JK",
	 },
      },
      trouble = {
         open = "<leader>pp",
         lsp_workspace_diagnostics = "<leader>pw",
         lsp_document_diagnostics = "<leader>pd",
         lsp_references = "<leader>pr",
         loclist = "<leader>pl",
         quickfix = "<leader>pq",
      },
      undo = { toggle_undo_tree = "<Leader>u" },
      window = {
         pick_window = "<leader>w",
         enter_shift_mode = "<C-w>m",
         shift_left = "<C-M-h>",
         shift_right = "<C-M-l>",
         shift_up = "<C-M-k>",
         shift_down = "<C-M-j>",
      },
      vimwiki = {
         -- global
         open_index = "<Leader>nn",
         open_tab = "<Leader>nt",
         select_open = "<Leader>ns",
         diary_index = "<Leader>ni",
         diary_entry = "<Leader>n<Leader>n",
         diary_tab = "<Leader>n<Leader>t",
         diary_yesterday = "<Leader>n<Leader>y",
         diary_tomorrow = "<Leader>n<Leader>m",
         diary_generate = "<Leader>n<Leader>i",
         -- local
         html = "<Leader>nh",
         html_browse = "<Leader>nhh",
         new = "<Leader>nw",
         delete = "<Leader>nd",
         rename = "<Leader>nr",
         next_link = "<Leader>]n",
         prev_link = "<Leader>]n",
      },
      zen = {
         ataraxis_mode = "<leader>zz",
	 focus_mode = "<leader>zf",
	 minimalistic_mode = "<leader>zm",
      },
   },
}

return M
